### ISSUE TITLE
Create the base project structure

### ISSUE THREAD

**Issue by marcos-wz** [wizeline/CA-Microservices-Go#1]
This issue is to discuss the best project structure following a hexagonal architecture.
    
# First approach       
- Follows first the &ldquo;who you are&rdquo; and then &ldquo;what is your type&rdquo; pattern.
- Clearly shows what is the domain of the project, eg. you can see at first sight that the project is about movies.
- Having a project whose directories are named according to the hexagonal architecture (eg. ports, application and adapters) could be confusing, especially for engineers who aren&rsquo;t completely familiar with the architecture, this approach goes for clear and simple names so that the project structure still can be understood without requiring previous knowledge of the hexagonal architecture.
- Easy to locate where something goes and where to look for it, eg. if you&rsquo;re looking for things related to the movie entity just go to the &ldquo;movies&rdquo; folder.
- We have separate repositories focused on the entities and their use cases preventing us from having one big repository through which we access all entities. This way is more decoupled to the point that we can have entities stored in separate databases.

```
            
                    .
                ├── core (src) /
                │   ├── movies/
                │   │   ├── infraestructure/
                │   │   │   ├── postgresql_movie_repository.go
                │   │   │   ├── http_handlers.go
                │   │   │   └── tests/
                │   │   │       └── (unit test here)
                │   │   ├── use_cases(services/application)/
                │   │   │   ├── add_movie.go
                │   │   │   ├── remove_movie.go
                │   │   │   ├── requests */
                │   │   │   │   └── add_movie_request.go
                │   │   │   └── tests/
                │   │   │       └── (unit test here)
                │   │   └── domain/
                │   │       ├── movie.go
                │   │       ├── movies_repository.go (interface for repositories)
                │   │       └── tests/
                │   │           └── (integration tests here)
                │   └── users/
                │       ├── infraestructure/
                │       │   ├── postgresql_user_repository.go
                │       │   ├── http_handlers.go
                │       │   └── tests
                │       ├── use_cases(services/application)/
                │       │   ├── add_user.go
                │       │   ├── remove_user.go
                │       │   ├── search_user.go
                │       │   ├── requests */
                │       │   │   └── add_user_request.go
                │       │   └── tests
                │       └── domain/
                │           ├── user.go
                │           └── user_repository.go (interface for repositories)
                ├── rest_api/
                │   └── routes.go (we setup the routes here)
                ├── main.go
                ├── dockerfile
                └── Makefile
```

Here the directories requests and responses in &ldquo;use<sub>cases</sub>&rdquo; are optional, they are suggested because we could define the DTOs (data transfer objects) we need them when an entity of a use case needs a complex input that isn&rsquo;t defined a domain entity:
        
- The input is not a complete domain entity or of a simple type (like a single ID).
- If it's complex enough it could require validation
- Thus in the request folder we could have the structs that could contain the input for a use case and would also be the perfect place to make input validations this way we don&rsquo;t need to define input validations inside the use cases.
- They don&rsquo;t need to be defined in a separate file or folder they also could be defined in the same file as the use<sub>case</sub>.
        
For example, you can find users with this necessity, source [reddit](https://www.reddit.com/r/Blazor/comments/wvv855/where_to_place_shared_dtos_in_clean_architecture/)
        
> Yeah that is exactly what I was doing, until I faced this situation where I have a complex query that doesn't return any domain model, because the query involves lots of join between tables, so the object it is returning doesn't represent a unique domain model but multiple ones. So I need the data layer to return a complex object that doesn't represent pure DB entity, that's why I need a DTO.

An example of the use of  DTOs can be found at this [repo](https://github.com/ashishjuyal/banking/tree/master/dto) so a request would look like this in go:
```
 package dto
            
import (
      "github.com/ashishjuyal/banking-lib/errs"
      "strings"
)
            
 type NewAccountRequest struct {
         CustomerId  string  `json:"customer_id"`
          AccountType string  `json:"account_type"`
          Amount      float64 `json:"amount"`
}
            
func (r NewAccountRequest) Validate() *errs.AppError {
         if r.Amount < 5000 {
            return errs.NewValidationError("To open a new account you need to deposit atleast 5000.00")
          }
          if strings.ToLower(r.AccountType) != "saving" && strings.ToLower(r.AccountType) != "checking" {
            return errs.NewValidationError("Account type should be checking or saving")
          }
         return nil
}
```

We could also have a response directory to define the output of the use cases in case that they could be complex structs different from the domains. Also they could be defined in the same file as the use case.
```
package dto
            
type NewAccountResponse struct {
    AccountId string `json:"account_id"`
}
```

A video of this structure can be found at this [youtube video](https://www.youtube.com/watch?v=y3MWfPDmVqo&t=886s)

# Second approach
This could be another approach, with this structure the first obvious thing is that we have a project that follows the hexagonal architecture, ins&rsquo;t my favorite given the obscurity of some folder names (you&rsquo;ll need to explain the complete architecture in the README for team members that don&rsquo;t have the complete context).
```
            .
            ├── .env
            ├── go.mod
            ├── go.sum
            ├── internal/
            │   ├── core/
            │   │   ├── domain/
            │   │   │   ├── movies.go
            │   │   │   └── users.go
            │   │   ├── ports/
            │   │   │   ├── movies_repository.go
            │   │   │   └── users_repository.go
            │   │   └── services/
            │   │       ├── movies.go
            │   │       └── users.go
            │   └── adapters/
            │       ├── http_handlers/
            │       │   ├── movies_handler.go
            │       │   └── users_handler.go
            │       ├── repository/
            │       │   └── postgres/
            │       │       ├── users_repository.go
            │       │       └── movies_repository.go
            │       └── tests
            └── rest_api/
                └── main.go
```
We could also apply the use of DTOs for validation creating requests and responses folder or just define them in the file for each service.

**Comment by maritza05** [comment]
Starting with the first approach for now but the structure could be modified in the future if needed.

**Comment by diegoOsornoC** [comment]
Hey @maritza05 @marcos-wz really good work on this!! I would love to work on an internal project using this kind of architecture.

A couple of suggestions

* Would be good to add what are the **benefits/drivers** of using this kind of architecture, as well as the **trade-offs**.
* Could be very useful to document some **DOES** and **DONT's** which could be a very simple guide to follow when someone that is not familiar with the architecture starts working on the project, ie. DON'T ever include business logic inside UseCase/Domain layers
* On the video you linked ([youtube video](https://www.youtube.com/watch?v=y3MWfPDmVqo&t=886s)), a **shared folder/package**  is mentioned, would be great to document what kind of components should be placed there.


Thanks for working on this and putting all this doc together, I'm looking forward to seeing the full API implementation.

**Comment by MigGrover** [comment]
Hey @marcos-wz @marcos-wz  I see that this is more of a Java structure :)
Things you should take into consideration, test in Go should always go in the same folder src and test, but I see there is a specific folder for this, which I see more commonly in Java, another thing to have in consideration that could make a complex structure is that at least from my experience a scalable structure should go something like core/layer/entity.
such as in the case of movies it should go something like core/usecase/movie.go, core/model/movie.go, core/controller/movie.go

if you go this way, you will end up having an object definition architecture, which is not the main focus of Go

As a reference, I would suggest this post 
https://github.com/manakuro/golang-clean-architecture Even though it is not the ultimate architecture, and in some cases, not all the layers are required, this has been in my experience the easiest way to create microservices in Golang.

**Comment by marcos-wz** [comment]
Final base Layout on [PR 16](https://github.com/wizeline/CA-Microservices-Go/pull/16)

**Comment by marcos-wz** [comment]
Merged
